### ISSUE TITLE
The output of rgg seems broken.

### ISSUE THREAD

**Issue by otakutyrant** [lilydjwg/search-and-view#13]
![2023-05-15-171424_957x637_scrot](https://github.com/lilydjwg/search-and-view/assets/64188229/ad09642d-1630-489c-81d3-82be307b1adb)

It appears whether I use Tmux, Zsh, and Alacrity.

**Comment by otakutyrant** [comment]
Btw, what does setproctitle use for?

**Comment by lilydjwg** [comment]
What's your version of less? It should be at least v570 to contain [this feature](https://github.com/gwsw/less/issues/54), or you can change line 144 of `agg` to use `-r` instead of `-R`.

Also, tmux needs to be [patched](https://github.com/tmux/tmux/pull/2621) for hyperlinks to work, and config:

```
set -sa terminal-overrides '*:Hls=\E]8;id=%p1%s;%p2%s\E\\:Hlr=\E]8;;\E\\'
```

setproctitle is for, well, setting process' title. It will be shown in the terminal title (or tmux window name), and setproctitle is used to change the default name (`python`) to a more distinguish one (`rgg` or `rgv`).

**Comment by otakutyrant** [comment]
How should I change the line 144 of `agg`? Is it not `rgg`?

**Comment by otakutyrant** [comment]
My less's version is `less 633 (PCRE2 regular expressions)`.

**Comment by lilydjwg** [comment]
Oh, `agg` is an old name. Yes, it should be `rgg`.

Your less is recent enough. Maybe it's because of tmux without the patch?

**Comment by otakutyrant** [comment]
I have changed [this line](https://github.com/lilydjwg/search-and-view/blob/master/rgg#L152) to use `-r` and executed `set -sa terminal-overrides '*:Hls=\E]8;id=%p1%s;%p2%s\E\\:Hlr=\E]8;;\E\\'`. But it doesn't work.

**Comment by lilydjwg** [comment]
Do you have this issue outside tmux?

Do you have this issue with `ls --hyperlink`?

**Comment by otakutyrant** [comment]
Yes. No.
![2023-05-15-211454_1864x401_scrot](https://github.com/lilydjwg/search-and-view/assets/64188229/f13dc2a3-3f43-42d3-bd39-794849ad5ad5)

**Comment by lilydjwg** [comment]
What about `ls --hyperlink=always | less -RFXM`?

**Comment by otakutyrant** [comment]
No matter whether I execute it in Tmux, it looks well.

**Comment by lilydjwg** [comment]
Which version of alacritty are you using?

**Comment by otakutyrant** [comment]
`alacritty 0.12.1 (5fdfd47f)`

Sorry for the late reply. I was on vacation!

**Comment by lilydjwg** [comment]
Weird. I'm using the exact version as you, but cannot reproduce the issue.
